server:
  port: 8080
  contextPath: /clinic
---
spring:
  profiles: default
datasource:
  properties:
    url: jdbc:mysql://localhost:3306/assignment3
    username: assignment
    password: softwaredesign
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: test
datasource:
  properties:
    url: jdbc:h2:~/test
    username: "SA"
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect