server:
  port: 8080
  contextPath: /clinic
---
spring:
  profiles: default, production
  datasource:
    initialize: false
datasource:
  properties:
    url: jdbc:mysql://localhost:3306/assignment3
    username: assignment
    password: softwaredesign
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
validation:
  allowedFirstDigit: 1,2,5,6
  minJDigit: 00
  maxJDigit: 52
  controlNumber: 279146358279
  idSeriesFile: ./allowed_id_ser.xml
---
spring:
  profiles: test
  datasource:
    initialize: false
datasource:
  properties:
    url: jdbc:h2:~/test
    username: "SA"
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
validation:
  allowedFirstDigit: 1,2,5,6
  minJDigit: 00
  maxJDigit: 52
  controlNumber: 279146358279
  idSeriesFile: ./allowed_id_ser.xml